# Generated by Django 3.2.3 on 2021-06-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0002_auto_20210614_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cliente',
        ),
    ]
